name: smart_hold_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  introduction_screen: ^3.1.9
  google_fonts: ^6.2.1
  lottie: ^2.3.2
  provider: ^6.0.5
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2



  flutter_secure_storage: ^9.0.0 
  dio: ^5.4.1   
  intl: ^0.20.2
  flutter_staggered_animations: ^1.1.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/parking.json
    - assets/images/caranimation.json
    - assets/images/aa.json
    - lib/Language/

